repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, scss, markdown]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint@^8.57.0
          - '@typescript-eslint/parser@^7.0.0'
          - '@typescript-eslint/eslint-plugin@^7.0.0'
          - 'eslint-config-prettier@^9.1.0'
          - 'eslint-plugin-react@^7.33.2'
          - 'eslint-plugin-react-hooks@^4.6.0'
